// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQ3pDJoxK1zXiDqRRKkDehgw0VtYMQrM',
    appId: '1:1064375266703:web:2d142627d946e22de8effa',
    messagingSenderId: '1064375266703',
    projectId: 'puoconnect',
    authDomain: 'puoconnect.firebaseapp.com',
    storageBucket: 'puoconnect.firebasestorage.app',
    measurementId: 'G-5C73TLR8C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxH1qh5Woxnn4P-YUSxp6-Q5b62_rO9s',
    appId: '1:1064375266703:android:575fb4b3792d25e8e8effa',
    messagingSenderId: '1064375266703',
    projectId: 'puoconnect',
    storageBucket: 'puoconnect.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHQQc8DMy5KK8uhlMFYSBm6P3CB8CX-c',
    appId: '1:1064375266703:ios:6aca73d96bbb86a5e8effa',
    messagingSenderId: '1064375266703',
    projectId: 'puoconnect',
    storageBucket: 'puoconnect.firebasestorage.app',
    iosBundleId: 'com.example.puoconnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpHQQc8DMy5KK8uhlMFYSBm6P3CB8CX-c',
    appId: '1:1064375266703:ios:6aca73d96bbb86a5e8effa',
    messagingSenderId: '1064375266703',
    projectId: 'puoconnect',
    storageBucket: 'puoconnect.firebasestorage.app',
    iosBundleId: 'com.example.puoconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeQ3pDJoxK1zXiDqRRKkDehgw0VtYMQrM',
    appId: '1:1064375266703:web:db8a374e57c6718de8effa',
    messagingSenderId: '1064375266703',
    projectId: 'puoconnect',
    authDomain: 'puoconnect.firebaseapp.com',
    storageBucket: 'puoconnect.firebasestorage.app',
    measurementId: 'G-X2NPBFFPY6',
  );
}
